<?php

namespace AccueilBundle\DataFixture\ORM;;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AccueilBundle\Entity\Pays;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadPays extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 1;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetaData(get_class(new Pays()))->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new Pays();
        $item1->setAlpha("AF");
        $item1->setNomFr("Afghanistan");
        $item1->setNomGb("Afghanistan");

        $this->addReference('_reference_Pays_1', $item1);

        $manager->persist($item1);

        $item2 = new Pays();
        $item2->setAlpha("AL");
        $item2->setNomFr("Albanie");
        $item2->setNomGb("Albania");

        $this->addReference('_reference_Pays_2', $item2);

        $manager->persist($item2);

        $item3 = new Pays();
        $item3->setAlpha("AQ");
        $item3->setNomFr("Antarctique");
        $item3->setNomGb("Antarctica");

        $this->addReference('_reference_Pays_3', $item3);

        $manager->persist($item3);

        $item4 = new Pays();
        $item4->setAlpha("DZ");
        $item4->setNomFr("Algérie");
        $item4->setNomGb("Algeria");

        $this->addReference('_reference_Pays_4', $item4);

        $manager->persist($item4);

        $item5 = new Pays();
        $item5->setAlpha("AS");
        $item5->setNomFr("Samoa Américaines");
        $item5->setNomGb("American Samoa");

        $this->addReference('_reference_Pays_5', $item5);

        $manager->persist($item5);

        $item6 = new Pays();
        $item6->setAlpha("AD");
        $item6->setNomFr("Andorre");
        $item6->setNomGb("Andorra");

        $this->addReference('_reference_Pays_6', $item6);

        $manager->persist($item6);

        $item7 = new Pays();
        $item7->setAlpha("AO");
        $item7->setNomFr("Angola");
        $item7->setNomGb("Angola");

        $this->addReference('_reference_Pays_7', $item7);

        $manager->persist($item7);

        $item8 = new Pays();
        $item8->setAlpha("AG");
        $item8->setNomFr("Antigua-et-Barbuda");
        $item8->setNomGb("Antigua and Barbuda");

        $this->addReference('_reference_Pays_8', $item8);

        $manager->persist($item8);

        $item9 = new Pays();
        $item9->setAlpha("AZ");
        $item9->setNomFr("Azerbaïdjan");
        $item9->setNomGb("Azerbaijan");

        $this->addReference('_reference_Pays_9', $item9);

        $manager->persist($item9);

        $item10 = new Pays();
        $item10->setAlpha("AR");
        $item10->setNomFr("Argentine");
        $item10->setNomGb("Argentina");

        $this->addReference('_reference_Pays_10', $item10);

        $manager->persist($item10);

        $item11 = new Pays();
        $item11->setAlpha("AU");
        $item11->setNomFr("Australie");
        $item11->setNomGb("Australia");

        $this->addReference('_reference_Pays_11', $item11);

        $manager->persist($item11);

        $item12 = new Pays();
        $item12->setAlpha("AT");
        $item12->setNomFr("Autriche");
        $item12->setNomGb("Austria");

        $this->addReference('_reference_Pays_12', $item12);

        $manager->persist($item12);

        $item13 = new Pays();
        $item13->setAlpha("BS");
        $item13->setNomFr("Bahamas");
        $item13->setNomGb("Bahamas");

        $this->addReference('_reference_Pays_13', $item13);

        $manager->persist($item13);

        $item14 = new Pays();
        $item14->setAlpha("BH");
        $item14->setNomFr("Bahreïn");
        $item14->setNomGb("Bahrain");

        $this->addReference('_reference_Pays_14', $item14);

        $manager->persist($item14);

        $item15 = new Pays();
        $item15->setAlpha("BD");
        $item15->setNomFr("Bangladesh");
        $item15->setNomGb("Bangladesh");

        $this->addReference('_reference_Pays_15', $item15);

        $manager->persist($item15);

        $item16 = new Pays();
        $item16->setAlpha("AM");
        $item16->setNomFr("Arménie");
        $item16->setNomGb("Armenia");

        $this->addReference('_reference_Pays_16', $item16);

        $manager->persist($item16);

        $item17 = new Pays();
        $item17->setAlpha("BB");
        $item17->setNomFr("Barbade");
        $item17->setNomGb("Barbados");

        $this->addReference('_reference_Pays_17', $item17);

        $manager->persist($item17);

        $item18 = new Pays();
        $item18->setAlpha("BE");
        $item18->setNomFr("Belgique");
        $item18->setNomGb("Belgium");

        $this->addReference('_reference_Pays_18', $item18);

        $manager->persist($item18);

        $item19 = new Pays();
        $item19->setAlpha("BM");
        $item19->setNomFr("Bermudes");
        $item19->setNomGb("Bermuda");

        $this->addReference('_reference_Pays_19', $item19);

        $manager->persist($item19);

        $item20 = new Pays();
        $item20->setAlpha("BT");
        $item20->setNomFr("Bhoutan");
        $item20->setNomGb("Bhutan");

        $this->addReference('_reference_Pays_20', $item20);

        $manager->persist($item20);

        $item21 = new Pays();
        $item21->setAlpha("BO");
        $item21->setNomFr("Bolivie");
        $item21->setNomGb("Bolivia");

        $this->addReference('_reference_Pays_21', $item21);

        $manager->persist($item21);

        $item22 = new Pays();
        $item22->setAlpha("BA");
        $item22->setNomFr("Bosnie-Herzégovine");
        $item22->setNomGb("Bosnia and Herzegovina");

        $this->addReference('_reference_Pays_22', $item22);

        $manager->persist($item22);

        $item23 = new Pays();
        $item23->setAlpha("BW");
        $item23->setNomFr("Botswana");
        $item23->setNomGb("Botswana");

        $this->addReference('_reference_Pays_23', $item23);

        $manager->persist($item23);

        $item24 = new Pays();
        $item24->setAlpha("BV");
        $item24->setNomFr("Île Bouvet");
        $item24->setNomGb("Bouvet Island");

        $this->addReference('_reference_Pays_24', $item24);

        $manager->persist($item24);

        $item25 = new Pays();
        $item25->setAlpha("BR");
        $item25->setNomFr("Brésil");
        $item25->setNomGb("Brazil");

        $this->addReference('_reference_Pays_25', $item25);

        $manager->persist($item25);

        $item26 = new Pays();
        $item26->setAlpha("BZ");
        $item26->setNomFr("Belize");
        $item26->setNomGb("Belize");

        $this->addReference('_reference_Pays_26', $item26);

        $manager->persist($item26);

        $item27 = new Pays();
        $item27->setAlpha("IO");
        $item27->setNomFr("Territoire Britannique de l'Océan Indien");
        $item27->setNomGb("British Indian Ocean Territory");

        $this->addReference('_reference_Pays_27', $item27);

        $manager->persist($item27);

        $item28 = new Pays();
        $item28->setAlpha("SB");
        $item28->setNomFr("Îles Salomon");
        $item28->setNomGb("Solomon Islands");

        $this->addReference('_reference_Pays_28', $item28);

        $manager->persist($item28);

        $item29 = new Pays();
        $item29->setAlpha("VG");
        $item29->setNomFr("Îles Vierges Britanniques");
        $item29->setNomGb("British Virgin Islands");

        $this->addReference('_reference_Pays_29', $item29);

        $manager->persist($item29);

        $item30 = new Pays();
        $item30->setAlpha("BN");
        $item30->setNomFr("Brunéi Darussalam");
        $item30->setNomGb("Brunei Darussalam");

        $this->addReference('_reference_Pays_30', $item30);

        $manager->persist($item30);

        $item31 = new Pays();
        $item31->setAlpha("BG");
        $item31->setNomFr("Bulgarie");
        $item31->setNomGb("Bulgaria");

        $this->addReference('_reference_Pays_31', $item31);

        $manager->persist($item31);

        $item32 = new Pays();
        $item32->setAlpha("MM");
        $item32->setNomFr("Myanmar");
        $item32->setNomGb("Myanmar");

        $this->addReference('_reference_Pays_32', $item32);

        $manager->persist($item32);

        $item33 = new Pays();
        $item33->setAlpha("BI");
        $item33->setNomFr("Burundi");
        $item33->setNomGb("Burundi");

        $this->addReference('_reference_Pays_33', $item33);

        $manager->persist($item33);

        $item34 = new Pays();
        $item34->setAlpha("BY");
        $item34->setNomFr("Bélarus");
        $item34->setNomGb("Belarus");

        $this->addReference('_reference_Pays_34', $item34);

        $manager->persist($item34);

        $item35 = new Pays();
        $item35->setAlpha("KH");
        $item35->setNomFr("Cambodge");
        $item35->setNomGb("Cambodia");

        $this->addReference('_reference_Pays_35', $item35);

        $manager->persist($item35);

        $item36 = new Pays();
        $item36->setAlpha("CM");
        $item36->setNomFr("Cameroun");
        $item36->setNomGb("Cameroon");

        $this->addReference('_reference_Pays_36', $item36);

        $manager->persist($item36);

        $item37 = new Pays();
        $item37->setAlpha("CA");
        $item37->setNomFr("Canada");
        $item37->setNomGb("Canada");

        $this->addReference('_reference_Pays_37', $item37);

        $manager->persist($item37);

        $item38 = new Pays();
        $item38->setAlpha("CV");
        $item38->setNomFr("Cap-vert");
        $item38->setNomGb("Cape Verde");

        $this->addReference('_reference_Pays_38', $item38);

        $manager->persist($item38);

        $item39 = new Pays();
        $item39->setAlpha("KY");
        $item39->setNomFr("Îles Caïmanes");
        $item39->setNomGb("Cayman Islands");

        $this->addReference('_reference_Pays_39', $item39);

        $manager->persist($item39);

        $item40 = new Pays();
        $item40->setAlpha("CF");
        $item40->setNomFr("République Centrafricaine");
        $item40->setNomGb("Central African");

        $this->addReference('_reference_Pays_40', $item40);

        $manager->persist($item40);

        $item41 = new Pays();
        $item41->setAlpha("LK");
        $item41->setNomFr("Sri Lanka");
        $item41->setNomGb("Sri Lanka");

        $this->addReference('_reference_Pays_41', $item41);

        $manager->persist($item41);

        $item42 = new Pays();
        $item42->setAlpha("TD");
        $item42->setNomFr("Tchad");
        $item42->setNomGb("Chad");

        $this->addReference('_reference_Pays_42', $item42);

        $manager->persist($item42);

        $item43 = new Pays();
        $item43->setAlpha("CL");
        $item43->setNomFr("Chili");
        $item43->setNomGb("Chile");

        $this->addReference('_reference_Pays_43', $item43);

        $manager->persist($item43);

        $item44 = new Pays();
        $item44->setAlpha("CN");
        $item44->setNomFr("Chine");
        $item44->setNomGb("China");

        $this->addReference('_reference_Pays_44', $item44);

        $manager->persist($item44);

        $item45 = new Pays();
        $item45->setAlpha("TW");
        $item45->setNomFr("Taïwan");
        $item45->setNomGb("Taiwan");

        $this->addReference('_reference_Pays_45', $item45);

        $manager->persist($item45);

        $item46 = new Pays();
        $item46->setAlpha("CX");
        $item46->setNomFr("Île Christmas");
        $item46->setNomGb("Christmas Island");

        $this->addReference('_reference_Pays_46', $item46);

        $manager->persist($item46);

        $item47 = new Pays();
        $item47->setAlpha("CC");
        $item47->setNomFr("Îles Cocos (Keeling)");
        $item47->setNomGb("Cocos (Keeling) Islands");

        $this->addReference('_reference_Pays_47', $item47);

        $manager->persist($item47);

        $item48 = new Pays();
        $item48->setAlpha("CO");
        $item48->setNomFr("Colombie");
        $item48->setNomGb("Colombia");

        $this->addReference('_reference_Pays_48', $item48);

        $manager->persist($item48);

        $item49 = new Pays();
        $item49->setAlpha("KM");
        $item49->setNomFr("Comores");
        $item49->setNomGb("Comoros");

        $this->addReference('_reference_Pays_49', $item49);

        $manager->persist($item49);

        $item50 = new Pays();
        $item50->setAlpha("YT");
        $item50->setNomFr("Mayotte");
        $item50->setNomGb("Mayotte");

        $this->addReference('_reference_Pays_50', $item50);

        $manager->persist($item50);

        $item51 = new Pays();
        $item51->setAlpha("CG");
        $item51->setNomFr("République du Congo");
        $item51->setNomGb("Republic of the Congo");

        $this->addReference('_reference_Pays_51', $item51);

        $manager->persist($item51);

        $item52 = new Pays();
        $item52->setAlpha("CD");
        $item52->setNomFr("République Démocratique du Congo");
        $item52->setNomGb("The Democratic Republic Of The Congo");

        $this->addReference('_reference_Pays_52', $item52);

        $manager->persist($item52);

        $item53 = new Pays();
        $item53->setAlpha("CK");
        $item53->setNomFr("Îles Cook");
        $item53->setNomGb("Cook Islands");

        $this->addReference('_reference_Pays_53', $item53);

        $manager->persist($item53);

        $item54 = new Pays();
        $item54->setAlpha("CR");
        $item54->setNomFr("Costa Rica");
        $item54->setNomGb("Costa Rica");

        $this->addReference('_reference_Pays_54', $item54);

        $manager->persist($item54);

        $item55 = new Pays();
        $item55->setAlpha("HR");
        $item55->setNomFr("Croatie");
        $item55->setNomGb("Croatia");

        $this->addReference('_reference_Pays_55', $item55);

        $manager->persist($item55);

        $item56 = new Pays();
        $item56->setAlpha("CU");
        $item56->setNomFr("Cuba");
        $item56->setNomGb("Cuba");

        $this->addReference('_reference_Pays_56', $item56);

        $manager->persist($item56);

        $item57 = new Pays();
        $item57->setAlpha("CY");
        $item57->setNomFr("Chypre");
        $item57->setNomGb("Cyprus");

        $this->addReference('_reference_Pays_57', $item57);

        $manager->persist($item57);

        $item58 = new Pays();
        $item58->setAlpha("CZ");
        $item58->setNomFr("République Tchèque");
        $item58->setNomGb("Czech Republic");

        $this->addReference('_reference_Pays_58', $item58);

        $manager->persist($item58);

        $item59 = new Pays();
        $item59->setAlpha("BJ");
        $item59->setNomFr("Bénin");
        $item59->setNomGb("Benin");

        $this->addReference('_reference_Pays_59', $item59);

        $manager->persist($item59);

        $item60 = new Pays();
        $item60->setAlpha("DK");
        $item60->setNomFr("Danemark");
        $item60->setNomGb("Denmark");

        $this->addReference('_reference_Pays_60', $item60);

        $manager->persist($item60);

        $item61 = new Pays();
        $item61->setAlpha("DM");
        $item61->setNomFr("Dominique");
        $item61->setNomGb("Dominica");

        $this->addReference('_reference_Pays_61', $item61);

        $manager->persist($item61);

        $item62 = new Pays();
        $item62->setAlpha("DO");
        $item62->setNomFr("République Dominicaine");
        $item62->setNomGb("Dominican Republic");

        $this->addReference('_reference_Pays_62', $item62);

        $manager->persist($item62);

        $item63 = new Pays();
        $item63->setAlpha("EC");
        $item63->setNomFr("Équateur");
        $item63->setNomGb("Ecuador");

        $this->addReference('_reference_Pays_63', $item63);

        $manager->persist($item63);

        $item64 = new Pays();
        $item64->setAlpha("SV");
        $item64->setNomFr("El Salvador");
        $item64->setNomGb("El Salvador");

        $this->addReference('_reference_Pays_64', $item64);

        $manager->persist($item64);

        $item65 = new Pays();
        $item65->setAlpha("GQ");
        $item65->setNomFr("Guinée Équatoriale");
        $item65->setNomGb("Equatorial Guinea");

        $this->addReference('_reference_Pays_65', $item65);

        $manager->persist($item65);

        $item66 = new Pays();
        $item66->setAlpha("ET");
        $item66->setNomFr("Éthiopie");
        $item66->setNomGb("Ethiopia");

        $this->addReference('_reference_Pays_66', $item66);

        $manager->persist($item66);

        $item67 = new Pays();
        $item67->setAlpha("ER");
        $item67->setNomFr("Érythrée");
        $item67->setNomGb("Eritrea");

        $this->addReference('_reference_Pays_67', $item67);

        $manager->persist($item67);

        $item68 = new Pays();
        $item68->setAlpha("EE");
        $item68->setNomFr("Estonie");
        $item68->setNomGb("Estonia");

        $this->addReference('_reference_Pays_68', $item68);

        $manager->persist($item68);

        $item69 = new Pays();
        $item69->setAlpha("FO");
        $item69->setNomFr("Îles Féroé");
        $item69->setNomGb("Faroe Islands");

        $this->addReference('_reference_Pays_69', $item69);

        $manager->persist($item69);

        $item70 = new Pays();
        $item70->setAlpha("FK");
        $item70->setNomFr("Îles (malvinas) Falkland");
        $item70->setNomGb("Falkland Islands");

        $this->addReference('_reference_Pays_70', $item70);

        $manager->persist($item70);

        $item71 = new Pays();
        $item71->setAlpha("GS");
        $item71->setNomFr("Géorgie du Sud et les Îles Sandwich du Sud");
        $item71->setNomGb("South Georgia and the South Sandwich Islands");

        $this->addReference('_reference_Pays_71', $item71);

        $manager->persist($item71);

        $item72 = new Pays();
        $item72->setAlpha("FJ");
        $item72->setNomFr("Fidji");
        $item72->setNomGb("Fiji");

        $this->addReference('_reference_Pays_72', $item72);

        $manager->persist($item72);

        $item73 = new Pays();
        $item73->setAlpha("FI");
        $item73->setNomFr("Finlande");
        $item73->setNomGb("Finland");

        $this->addReference('_reference_Pays_73', $item73);

        $manager->persist($item73);

        $item74 = new Pays();
        $item74->setAlpha("AX");
        $item74->setNomFr("Îles Åland");
        $item74->setNomGb("Åland Islands");

        $this->addReference('_reference_Pays_74', $item74);

        $manager->persist($item74);

        $item75 = new Pays();
        $item75->setAlpha("FR");
        $item75->setNomFr("France");
        $item75->setNomGb("France");

        $this->addReference('_reference_Pays_75', $item75);

        $manager->persist($item75);

        $item76 = new Pays();
        $item76->setAlpha("GF");
        $item76->setNomFr("Guyane Française");
        $item76->setNomGb("French Guiana");

        $this->addReference('_reference_Pays_76', $item76);

        $manager->persist($item76);

        $item77 = new Pays();
        $item77->setAlpha("PF");
        $item77->setNomFr("Polynésie Française");
        $item77->setNomGb("French Polynesia");

        $this->addReference('_reference_Pays_77', $item77);

        $manager->persist($item77);

        $item78 = new Pays();
        $item78->setAlpha("TF");
        $item78->setNomFr("Terres Australes Françaises");
        $item78->setNomGb("French Southern Territories");

        $this->addReference('_reference_Pays_78', $item78);

        $manager->persist($item78);

        $item79 = new Pays();
        $item79->setAlpha("DJ");
        $item79->setNomFr("Djibouti");
        $item79->setNomGb("Djibouti");

        $this->addReference('_reference_Pays_79', $item79);

        $manager->persist($item79);

        $item80 = new Pays();
        $item80->setAlpha("GA");
        $item80->setNomFr("Gabon");
        $item80->setNomGb("Gabon");

        $this->addReference('_reference_Pays_80', $item80);

        $manager->persist($item80);

        $item81 = new Pays();
        $item81->setAlpha("GE");
        $item81->setNomFr("Géorgie");
        $item81->setNomGb("Georgia");

        $this->addReference('_reference_Pays_81', $item81);

        $manager->persist($item81);

        $item82 = new Pays();
        $item82->setAlpha("GM");
        $item82->setNomFr("Gambie");
        $item82->setNomGb("Gambia");

        $this->addReference('_reference_Pays_82', $item82);

        $manager->persist($item82);

        $item83 = new Pays();
        $item83->setAlpha("PS");
        $item83->setNomFr("Territoire Palestinien Occupé");
        $item83->setNomGb("Occupied Palestinian Territory");

        $this->addReference('_reference_Pays_83', $item83);

        $manager->persist($item83);

        $item84 = new Pays();
        $item84->setAlpha("DE");
        $item84->setNomFr("Allemagne");
        $item84->setNomGb("Germany");

        $this->addReference('_reference_Pays_84', $item84);

        $manager->persist($item84);

        $item85 = new Pays();
        $item85->setAlpha("GH");
        $item85->setNomFr("Ghana");
        $item85->setNomGb("Ghana");

        $this->addReference('_reference_Pays_85', $item85);

        $manager->persist($item85);

        $item86 = new Pays();
        $item86->setAlpha("GI");
        $item86->setNomFr("Gibraltar");
        $item86->setNomGb("Gibraltar");

        $this->addReference('_reference_Pays_86', $item86);

        $manager->persist($item86);

        $item87 = new Pays();
        $item87->setAlpha("KI");
        $item87->setNomFr("Kiribati");
        $item87->setNomGb("Kiribati");

        $this->addReference('_reference_Pays_87', $item87);

        $manager->persist($item87);

        $item88 = new Pays();
        $item88->setAlpha("GR");
        $item88->setNomFr("Grèce");
        $item88->setNomGb("Greece");

        $this->addReference('_reference_Pays_88', $item88);

        $manager->persist($item88);

        $item89 = new Pays();
        $item89->setAlpha("GL");
        $item89->setNomFr("Groenland");
        $item89->setNomGb("Greenland");

        $this->addReference('_reference_Pays_89', $item89);

        $manager->persist($item89);

        $item90 = new Pays();
        $item90->setAlpha("GD");
        $item90->setNomFr("Grenade");
        $item90->setNomGb("Grenada");

        $this->addReference('_reference_Pays_90', $item90);

        $manager->persist($item90);

        $item91 = new Pays();
        $item91->setAlpha("GP");
        $item91->setNomFr("Guadeloupe");
        $item91->setNomGb("Guadeloupe");

        $this->addReference('_reference_Pays_91', $item91);

        $manager->persist($item91);

        $item92 = new Pays();
        $item92->setAlpha("GU");
        $item92->setNomFr("Guam");
        $item92->setNomGb("Guam");

        $this->addReference('_reference_Pays_92', $item92);

        $manager->persist($item92);

        $item93 = new Pays();
        $item93->setAlpha("GT");
        $item93->setNomFr("Guatemala");
        $item93->setNomGb("Guatemala");

        $this->addReference('_reference_Pays_93', $item93);

        $manager->persist($item93);

        $item94 = new Pays();
        $item94->setAlpha("GN");
        $item94->setNomFr("Guinée");
        $item94->setNomGb("Guinea");

        $this->addReference('_reference_Pays_94', $item94);

        $manager->persist($item94);

        $item95 = new Pays();
        $item95->setAlpha("GY");
        $item95->setNomFr("Guyana");
        $item95->setNomGb("Guyana");

        $this->addReference('_reference_Pays_95', $item95);

        $manager->persist($item95);

        $item96 = new Pays();
        $item96->setAlpha("HT");
        $item96->setNomFr("Haïti");
        $item96->setNomGb("Haiti");

        $this->addReference('_reference_Pays_96', $item96);

        $manager->persist($item96);

        $item97 = new Pays();
        $item97->setAlpha("HM");
        $item97->setNomFr("Îles Heard et Mcdonald");
        $item97->setNomGb("Heard Island and McDonald Islands");

        $this->addReference('_reference_Pays_97', $item97);

        $manager->persist($item97);

        $item98 = new Pays();
        $item98->setAlpha("VA");
        $item98->setNomFr("Saint-Siège (état de la Cité du Vatican)");
        $item98->setNomGb("Vatican City State");

        $this->addReference('_reference_Pays_98', $item98);

        $manager->persist($item98);

        $item99 = new Pays();
        $item99->setAlpha("HN");
        $item99->setNomFr("Honduras");
        $item99->setNomGb("Honduras");

        $this->addReference('_reference_Pays_99', $item99);

        $manager->persist($item99);

        $item100 = new Pays();
        $item100->setAlpha("HK");
        $item100->setNomFr("Hong-Kong");
        $item100->setNomGb("Hong Kong");

        $this->addReference('_reference_Pays_100', $item100);

        $manager->persist($item100);

        $item101 = new Pays();
        $item101->setAlpha("HU");
        $item101->setNomFr("Hongrie");
        $item101->setNomGb("Hungary");

        $this->addReference('_reference_Pays_101', $item101);

        $manager->persist($item101);

        $item102 = new Pays();
        $item102->setAlpha("IS");
        $item102->setNomFr("Islande");
        $item102->setNomGb("Iceland");

        $this->addReference('_reference_Pays_102', $item102);

        $manager->persist($item102);

        $item103 = new Pays();
        $item103->setAlpha("IN");
        $item103->setNomFr("Inde");
        $item103->setNomGb("India");

        $this->addReference('_reference_Pays_103', $item103);

        $manager->persist($item103);

        $item104 = new Pays();
        $item104->setAlpha("ID");
        $item104->setNomFr("Indonésie");
        $item104->setNomGb("Indonesia");

        $this->addReference('_reference_Pays_104', $item104);

        $manager->persist($item104);

        $item105 = new Pays();
        $item105->setAlpha("IR");
        $item105->setNomFr("République Islamique d'Iran");
        $item105->setNomGb("Islamic Republic of Iran");

        $this->addReference('_reference_Pays_105', $item105);

        $manager->persist($item105);

        $item106 = new Pays();
        $item106->setAlpha("IQ");
        $item106->setNomFr("Iraq");
        $item106->setNomGb("Iraq");

        $this->addReference('_reference_Pays_106', $item106);

        $manager->persist($item106);

        $item107 = new Pays();
        $item107->setAlpha("IE");
        $item107->setNomFr("Irlande");
        $item107->setNomGb("Ireland");

        $this->addReference('_reference_Pays_107', $item107);

        $manager->persist($item107);

        $item108 = new Pays();
        $item108->setAlpha("IL");
        $item108->setNomFr("Israël");
        $item108->setNomGb("Israel");

        $this->addReference('_reference_Pays_108', $item108);

        $manager->persist($item108);

        $item109 = new Pays();
        $item109->setAlpha("IT");
        $item109->setNomFr("Italie");
        $item109->setNomGb("Italy");

        $this->addReference('_reference_Pays_109', $item109);

        $manager->persist($item109);

        $item110 = new Pays();
        $item110->setAlpha("CI");
        $item110->setNomFr("Côte d'Ivoire");
        $item110->setNomGb("Côte d'Ivoire");

        $this->addReference('_reference_Pays_110', $item110);

        $manager->persist($item110);

        $item111 = new Pays();
        $item111->setAlpha("JM");
        $item111->setNomFr("Jamaïque");
        $item111->setNomGb("Jamaica");

        $this->addReference('_reference_Pays_111', $item111);

        $manager->persist($item111);

        $item112 = new Pays();
        $item112->setAlpha("JP");
        $item112->setNomFr("Japon");
        $item112->setNomGb("Japan");

        $this->addReference('_reference_Pays_112', $item112);

        $manager->persist($item112);

        $item113 = new Pays();
        $item113->setAlpha("KZ");
        $item113->setNomFr("Kazakhstan");
        $item113->setNomGb("Kazakhstan");

        $this->addReference('_reference_Pays_113', $item113);

        $manager->persist($item113);

        $item114 = new Pays();
        $item114->setAlpha("JO");
        $item114->setNomFr("Jordanie");
        $item114->setNomGb("Jordan");

        $this->addReference('_reference_Pays_114', $item114);

        $manager->persist($item114);

        $item115 = new Pays();
        $item115->setAlpha("KE");
        $item115->setNomFr("Kenya");
        $item115->setNomGb("Kenya");

        $this->addReference('_reference_Pays_115', $item115);

        $manager->persist($item115);

        $item116 = new Pays();
        $item116->setAlpha("KP");
        $item116->setNomFr("République Populaire Démocratique de Corée");
        $item116->setNomGb("Democratic People's Republic of Korea");

        $this->addReference('_reference_Pays_116', $item116);

        $manager->persist($item116);

        $item117 = new Pays();
        $item117->setAlpha("KR");
        $item117->setNomFr("République de Corée");
        $item117->setNomGb("Republic of Korea");

        $this->addReference('_reference_Pays_117', $item117);

        $manager->persist($item117);

        $item118 = new Pays();
        $item118->setAlpha("KW");
        $item118->setNomFr("Koweït");
        $item118->setNomGb("Kuwait");

        $this->addReference('_reference_Pays_118', $item118);

        $manager->persist($item118);

        $item119 = new Pays();
        $item119->setAlpha("KG");
        $item119->setNomFr("Kirghizistan");
        $item119->setNomGb("Kyrgyzstan");

        $this->addReference('_reference_Pays_119', $item119);

        $manager->persist($item119);

        $item120 = new Pays();
        $item120->setAlpha("LA");
        $item120->setNomFr("République Démocratique Populaire Lao");
        $item120->setNomGb("Lao People's Democratic Republic");

        $this->addReference('_reference_Pays_120', $item120);

        $manager->persist($item120);

        $item121 = new Pays();
        $item121->setAlpha("LB");
        $item121->setNomFr("Liban");
        $item121->setNomGb("Lebanon");

        $this->addReference('_reference_Pays_121', $item121);

        $manager->persist($item121);

        $item122 = new Pays();
        $item122->setAlpha("LS");
        $item122->setNomFr("Lesotho");
        $item122->setNomGb("Lesotho");

        $this->addReference('_reference_Pays_122', $item122);

        $manager->persist($item122);

        $item123 = new Pays();
        $item123->setAlpha("LV");
        $item123->setNomFr("Lettonie");
        $item123->setNomGb("Latvia");

        $this->addReference('_reference_Pays_123', $item123);

        $manager->persist($item123);

        $item124 = new Pays();
        $item124->setAlpha("LR");
        $item124->setNomFr("Libéria");
        $item124->setNomGb("Liberia");

        $this->addReference('_reference_Pays_124', $item124);

        $manager->persist($item124);

        $item125 = new Pays();
        $item125->setAlpha("LY");
        $item125->setNomFr("Jamahiriya Arabe Libyenne");
        $item125->setNomGb("Libyan Arab Jamahiriya");

        $this->addReference('_reference_Pays_125', $item125);

        $manager->persist($item125);

        $item126 = new Pays();
        $item126->setAlpha("LI");
        $item126->setNomFr("Liechtenstein");
        $item126->setNomGb("Liechtenstein");

        $this->addReference('_reference_Pays_126', $item126);

        $manager->persist($item126);

        $item127 = new Pays();
        $item127->setAlpha("LT");
        $item127->setNomFr("Lituanie");
        $item127->setNomGb("Lithuania");

        $this->addReference('_reference_Pays_127', $item127);

        $manager->persist($item127);

        $item128 = new Pays();
        $item128->setAlpha("LU");
        $item128->setNomFr("Luxembourg");
        $item128->setNomGb("Luxembourg");

        $this->addReference('_reference_Pays_128', $item128);

        $manager->persist($item128);

        $item129 = new Pays();
        $item129->setAlpha("MO");
        $item129->setNomFr("Macao");
        $item129->setNomGb("Macao");

        $this->addReference('_reference_Pays_129', $item129);

        $manager->persist($item129);

        $item130 = new Pays();
        $item130->setAlpha("MG");
        $item130->setNomFr("Madagascar");
        $item130->setNomGb("Madagascar");

        $this->addReference('_reference_Pays_130', $item130);

        $manager->persist($item130);

        $item131 = new Pays();
        $item131->setAlpha("MW");
        $item131->setNomFr("Malawi");
        $item131->setNomGb("Malawi");

        $this->addReference('_reference_Pays_131', $item131);

        $manager->persist($item131);

        $item132 = new Pays();
        $item132->setAlpha("MY");
        $item132->setNomFr("Malaisie");
        $item132->setNomGb("Malaysia");

        $this->addReference('_reference_Pays_132', $item132);

        $manager->persist($item132);

        $item133 = new Pays();
        $item133->setAlpha("MV");
        $item133->setNomFr("Maldives");
        $item133->setNomGb("Maldives");

        $this->addReference('_reference_Pays_133', $item133);

        $manager->persist($item133);

        $item134 = new Pays();
        $item134->setAlpha("ML");
        $item134->setNomFr("Mali");
        $item134->setNomGb("Mali");

        $this->addReference('_reference_Pays_134', $item134);

        $manager->persist($item134);

        $item135 = new Pays();
        $item135->setAlpha("MT");
        $item135->setNomFr("Malte");
        $item135->setNomGb("Malta");

        $this->addReference('_reference_Pays_135', $item135);

        $manager->persist($item135);

        $item136 = new Pays();
        $item136->setAlpha("MQ");
        $item136->setNomFr("Martinique");
        $item136->setNomGb("Martinique");

        $this->addReference('_reference_Pays_136', $item136);

        $manager->persist($item136);

        $item137 = new Pays();
        $item137->setAlpha("MR");
        $item137->setNomFr("Mauritanie");
        $item137->setNomGb("Mauritania");

        $this->addReference('_reference_Pays_137', $item137);

        $manager->persist($item137);

        $item138 = new Pays();
        $item138->setAlpha("MU");
        $item138->setNomFr("Maurice");
        $item138->setNomGb("Mauritius");

        $this->addReference('_reference_Pays_138', $item138);

        $manager->persist($item138);

        $item139 = new Pays();
        $item139->setAlpha("MX");
        $item139->setNomFr("Mexique");
        $item139->setNomGb("Mexico");

        $this->addReference('_reference_Pays_139', $item139);

        $manager->persist($item139);

        $item140 = new Pays();
        $item140->setAlpha("MC");
        $item140->setNomFr("Monaco");
        $item140->setNomGb("Monaco");

        $this->addReference('_reference_Pays_140', $item140);

        $manager->persist($item140);

        $item141 = new Pays();
        $item141->setAlpha("MN");
        $item141->setNomFr("Mongolie");
        $item141->setNomGb("Mongolia");

        $this->addReference('_reference_Pays_141', $item141);

        $manager->persist($item141);

        $item142 = new Pays();
        $item142->setAlpha("MD");
        $item142->setNomFr("République de Moldova");
        $item142->setNomGb("Republic of Moldova");

        $this->addReference('_reference_Pays_142', $item142);

        $manager->persist($item142);

        $item143 = new Pays();
        $item143->setAlpha("MS");
        $item143->setNomFr("Montserrat");
        $item143->setNomGb("Montserrat");

        $this->addReference('_reference_Pays_143', $item143);

        $manager->persist($item143);

        $item144 = new Pays();
        $item144->setAlpha("MA");
        $item144->setNomFr("Maroc");
        $item144->setNomGb("Morocco");

        $this->addReference('_reference_Pays_144', $item144);

        $manager->persist($item144);

        $item145 = new Pays();
        $item145->setAlpha("MZ");
        $item145->setNomFr("Mozambique");
        $item145->setNomGb("Mozambique");

        $this->addReference('_reference_Pays_145', $item145);

        $manager->persist($item145);

        $item146 = new Pays();
        $item146->setAlpha("OM");
        $item146->setNomFr("Oman");
        $item146->setNomGb("Oman");

        $this->addReference('_reference_Pays_146', $item146);

        $manager->persist($item146);

        $item147 = new Pays();
        $item147->setAlpha("NA");
        $item147->setNomFr("Namibie");
        $item147->setNomGb("Namibia");

        $this->addReference('_reference_Pays_147', $item147);

        $manager->persist($item147);

        $item148 = new Pays();
        $item148->setAlpha("NR");
        $item148->setNomFr("Nauru");
        $item148->setNomGb("Nauru");

        $this->addReference('_reference_Pays_148', $item148);

        $manager->persist($item148);

        $item149 = new Pays();
        $item149->setAlpha("NP");
        $item149->setNomFr("Népal");
        $item149->setNomGb("Nepal");

        $this->addReference('_reference_Pays_149', $item149);

        $manager->persist($item149);

        $item150 = new Pays();
        $item150->setAlpha("NL");
        $item150->setNomFr("Pays-Bas");
        $item150->setNomGb("Netherlands");

        $this->addReference('_reference_Pays_150', $item150);

        $manager->persist($item150);

        $item151 = new Pays();
        $item151->setAlpha("AN");
        $item151->setNomFr("Antilles Néerlandaises");
        $item151->setNomGb("Netherlands Antilles");

        $this->addReference('_reference_Pays_151', $item151);

        $manager->persist($item151);

        $item152 = new Pays();
        $item152->setAlpha("AW");
        $item152->setNomFr("Aruba");
        $item152->setNomGb("Aruba");

        $this->addReference('_reference_Pays_152', $item152);

        $manager->persist($item152);

        $item153 = new Pays();
        $item153->setAlpha("NC");
        $item153->setNomFr("Nouvelle-Calédonie");
        $item153->setNomGb("New Caledonia");

        $this->addReference('_reference_Pays_153', $item153);

        $manager->persist($item153);

        $item154 = new Pays();
        $item154->setAlpha("VU");
        $item154->setNomFr("Vanuatu");
        $item154->setNomGb("Vanuatu");

        $this->addReference('_reference_Pays_154', $item154);

        $manager->persist($item154);

        $item155 = new Pays();
        $item155->setAlpha("NZ");
        $item155->setNomFr("Nouvelle-Zélande");
        $item155->setNomGb("New Zealand");

        $this->addReference('_reference_Pays_155', $item155);

        $manager->persist($item155);

        $item156 = new Pays();
        $item156->setAlpha("NI");
        $item156->setNomFr("Nicaragua");
        $item156->setNomGb("Nicaragua");

        $this->addReference('_reference_Pays_156', $item156);

        $manager->persist($item156);

        $item157 = new Pays();
        $item157->setAlpha("NE");
        $item157->setNomFr("Niger");
        $item157->setNomGb("Niger");

        $this->addReference('_reference_Pays_157', $item157);

        $manager->persist($item157);

        $item158 = new Pays();
        $item158->setAlpha("NG");
        $item158->setNomFr("Nigéria");
        $item158->setNomGb("Nigeria");

        $this->addReference('_reference_Pays_158', $item158);

        $manager->persist($item158);

        $item159 = new Pays();
        $item159->setAlpha("NU");
        $item159->setNomFr("Niué");
        $item159->setNomGb("Niue");

        $this->addReference('_reference_Pays_159', $item159);

        $manager->persist($item159);

        $item160 = new Pays();
        $item160->setAlpha("NF");
        $item160->setNomFr("Île Norfolk");
        $item160->setNomGb("Norfolk Island");

        $this->addReference('_reference_Pays_160', $item160);

        $manager->persist($item160);

        $item161 = new Pays();
        $item161->setAlpha("NO");
        $item161->setNomFr("Norvège");
        $item161->setNomGb("Norway");

        $this->addReference('_reference_Pays_161', $item161);

        $manager->persist($item161);

        $item162 = new Pays();
        $item162->setAlpha("MP");
        $item162->setNomFr("Îles Mariannes du Nord");
        $item162->setNomGb("Northern Mariana Islands");

        $this->addReference('_reference_Pays_162', $item162);

        $manager->persist($item162);

        $item163 = new Pays();
        $item163->setAlpha("UM");
        $item163->setNomFr("Îles Mineures Éloignées des États-Unis");
        $item163->setNomGb("United States Minor Outlying Islands");

        $this->addReference('_reference_Pays_163', $item163);

        $manager->persist($item163);

        $item164 = new Pays();
        $item164->setAlpha("FM");
        $item164->setNomFr("États Fédérés de Micronésie");
        $item164->setNomGb("Federated States of Micronesia");

        $this->addReference('_reference_Pays_164', $item164);

        $manager->persist($item164);

        $item165 = new Pays();
        $item165->setAlpha("MH");
        $item165->setNomFr("Îles Marshall");
        $item165->setNomGb("Marshall Islands");

        $this->addReference('_reference_Pays_165', $item165);

        $manager->persist($item165);

        $item166 = new Pays();
        $item166->setAlpha("PW");
        $item166->setNomFr("Palaos");
        $item166->setNomGb("Palau");

        $this->addReference('_reference_Pays_166', $item166);

        $manager->persist($item166);

        $item167 = new Pays();
        $item167->setAlpha("PK");
        $item167->setNomFr("Pakistan");
        $item167->setNomGb("Pakistan");

        $this->addReference('_reference_Pays_167', $item167);

        $manager->persist($item167);

        $item168 = new Pays();
        $item168->setAlpha("PA");
        $item168->setNomFr("Panama");
        $item168->setNomGb("Panama");

        $this->addReference('_reference_Pays_168', $item168);

        $manager->persist($item168);

        $item169 = new Pays();
        $item169->setAlpha("PG");
        $item169->setNomFr("Papouasie-Nouvelle-Guinée");
        $item169->setNomGb("Papua New Guinea");

        $this->addReference('_reference_Pays_169', $item169);

        $manager->persist($item169);

        $item170 = new Pays();
        $item170->setAlpha("PY");
        $item170->setNomFr("Paraguay");
        $item170->setNomGb("Paraguay");

        $this->addReference('_reference_Pays_170', $item170);

        $manager->persist($item170);

        $item171 = new Pays();
        $item171->setAlpha("PE");
        $item171->setNomFr("Pérou");
        $item171->setNomGb("Peru");

        $this->addReference('_reference_Pays_171', $item171);

        $manager->persist($item171);

        $item172 = new Pays();
        $item172->setAlpha("PH");
        $item172->setNomFr("Philippines");
        $item172->setNomGb("Philippines");

        $this->addReference('_reference_Pays_172', $item172);

        $manager->persist($item172);

        $item173 = new Pays();
        $item173->setAlpha("PN");
        $item173->setNomFr("Pitcairn");
        $item173->setNomGb("Pitcairn");

        $this->addReference('_reference_Pays_173', $item173);

        $manager->persist($item173);

        $item174 = new Pays();
        $item174->setAlpha("PL");
        $item174->setNomFr("Pologne");
        $item174->setNomGb("Poland");

        $this->addReference('_reference_Pays_174', $item174);

        $manager->persist($item174);

        $item175 = new Pays();
        $item175->setAlpha("PT");
        $item175->setNomFr("Portugal");
        $item175->setNomGb("Portugal");

        $this->addReference('_reference_Pays_175', $item175);

        $manager->persist($item175);

        $item176 = new Pays();
        $item176->setAlpha("GW");
        $item176->setNomFr("Guinée-Bissau");
        $item176->setNomGb("Guinea-Bissau");

        $this->addReference('_reference_Pays_176', $item176);

        $manager->persist($item176);

        $item177 = new Pays();
        $item177->setAlpha("TL");
        $item177->setNomFr("Timor-Leste");
        $item177->setNomGb("Timor-Leste");

        $this->addReference('_reference_Pays_177', $item177);

        $manager->persist($item177);

        $item178 = new Pays();
        $item178->setAlpha("PR");
        $item178->setNomFr("Porto Rico");
        $item178->setNomGb("Puerto Rico");

        $this->addReference('_reference_Pays_178', $item178);

        $manager->persist($item178);

        $item179 = new Pays();
        $item179->setAlpha("QA");
        $item179->setNomFr("Qatar");
        $item179->setNomGb("Qatar");

        $this->addReference('_reference_Pays_179', $item179);

        $manager->persist($item179);

        $item180 = new Pays();
        $item180->setAlpha("RE");
        $item180->setNomFr("Réunion");
        $item180->setNomGb("Réunion");

        $this->addReference('_reference_Pays_180', $item180);

        $manager->persist($item180);

        $item181 = new Pays();
        $item181->setAlpha("RO");
        $item181->setNomFr("Roumanie");
        $item181->setNomGb("Romania");

        $this->addReference('_reference_Pays_181', $item181);

        $manager->persist($item181);

        $item182 = new Pays();
        $item182->setAlpha("RU");
        $item182->setNomFr("Fédération de Russie");
        $item182->setNomGb("Russian Federation");

        $this->addReference('_reference_Pays_182', $item182);

        $manager->persist($item182);

        $item183 = new Pays();
        $item183->setAlpha("RW");
        $item183->setNomFr("Rwanda");
        $item183->setNomGb("Rwanda");

        $this->addReference('_reference_Pays_183', $item183);

        $manager->persist($item183);

        $item184 = new Pays();
        $item184->setAlpha("SH");
        $item184->setNomFr("Sainte-Hélène");
        $item184->setNomGb("Saint Helena");

        $this->addReference('_reference_Pays_184', $item184);

        $manager->persist($item184);

        $item185 = new Pays();
        $item185->setAlpha("KN");
        $item185->setNomFr("Saint-Kitts-et-Nevis");
        $item185->setNomGb("Saint Kitts and Nevis");

        $this->addReference('_reference_Pays_185', $item185);

        $manager->persist($item185);

        $item186 = new Pays();
        $item186->setAlpha("AI");
        $item186->setNomFr("Anguilla");
        $item186->setNomGb("Anguilla");

        $this->addReference('_reference_Pays_186', $item186);

        $manager->persist($item186);

        $item187 = new Pays();
        $item187->setAlpha("LC");
        $item187->setNomFr("Sainte-Lucie");
        $item187->setNomGb("Saint Lucia");

        $this->addReference('_reference_Pays_187', $item187);

        $manager->persist($item187);

        $item188 = new Pays();
        $item188->setAlpha("PM");
        $item188->setNomFr("Saint-Pierre-et-Miquelon");
        $item188->setNomGb("Saint-Pierre and Miquelon");

        $this->addReference('_reference_Pays_188', $item188);

        $manager->persist($item188);

        $item189 = new Pays();
        $item189->setAlpha("VC");
        $item189->setNomFr("Saint-Vincent-et-les Grenadines");
        $item189->setNomGb("Saint Vincent and the Grenadines");

        $this->addReference('_reference_Pays_189', $item189);

        $manager->persist($item189);

        $item190 = new Pays();
        $item190->setAlpha("SM");
        $item190->setNomFr("Saint-Marin");
        $item190->setNomGb("San Marino");

        $this->addReference('_reference_Pays_190', $item190);

        $manager->persist($item190);

        $item191 = new Pays();
        $item191->setAlpha("ST");
        $item191->setNomFr("Sao Tomé-et-Principe");
        $item191->setNomGb("Sao Tome and Principe");

        $this->addReference('_reference_Pays_191', $item191);

        $manager->persist($item191);

        $item192 = new Pays();
        $item192->setAlpha("SA");
        $item192->setNomFr("Arabie Saoudite");
        $item192->setNomGb("Saudi Arabia");

        $this->addReference('_reference_Pays_192', $item192);

        $manager->persist($item192);

        $item193 = new Pays();
        $item193->setAlpha("SN");
        $item193->setNomFr("Sénégal");
        $item193->setNomGb("Senegal");

        $this->addReference('_reference_Pays_193', $item193);

        $manager->persist($item193);

        $item194 = new Pays();
        $item194->setAlpha("SC");
        $item194->setNomFr("Seychelles");
        $item194->setNomGb("Seychelles");

        $this->addReference('_reference_Pays_194', $item194);

        $manager->persist($item194);

        $item195 = new Pays();
        $item195->setAlpha("SL");
        $item195->setNomFr("Sierra Leone");
        $item195->setNomGb("Sierra Leone");

        $this->addReference('_reference_Pays_195', $item195);

        $manager->persist($item195);

        $item196 = new Pays();
        $item196->setAlpha("SG");
        $item196->setNomFr("Singapour");
        $item196->setNomGb("Singapore");

        $this->addReference('_reference_Pays_196', $item196);

        $manager->persist($item196);

        $item197 = new Pays();
        $item197->setAlpha("SK");
        $item197->setNomFr("Slovaquie");
        $item197->setNomGb("Slovakia");

        $this->addReference('_reference_Pays_197', $item197);

        $manager->persist($item197);

        $item198 = new Pays();
        $item198->setAlpha("VN");
        $item198->setNomFr("Viet Nam");
        $item198->setNomGb("Vietnam");

        $this->addReference('_reference_Pays_198', $item198);

        $manager->persist($item198);

        $item199 = new Pays();
        $item199->setAlpha("SI");
        $item199->setNomFr("Slovénie");
        $item199->setNomGb("Slovenia");

        $this->addReference('_reference_Pays_199', $item199);

        $manager->persist($item199);

        $item200 = new Pays();
        $item200->setAlpha("SO");
        $item200->setNomFr("Somalie");
        $item200->setNomGb("Somalia");

        $this->addReference('_reference_Pays_200', $item200);

        $manager->persist($item200);

        $item201 = new Pays();
        $item201->setAlpha("ZA");
        $item201->setNomFr("Afrique du Sud");
        $item201->setNomGb("South Africa");

        $this->addReference('_reference_Pays_201', $item201);

        $manager->persist($item201);

        $item202 = new Pays();
        $item202->setAlpha("ZW");
        $item202->setNomFr("Zimbabwe");
        $item202->setNomGb("Zimbabwe");

        $this->addReference('_reference_Pays_202', $item202);

        $manager->persist($item202);

        $item203 = new Pays();
        $item203->setAlpha("ES");
        $item203->setNomFr("Espagne");
        $item203->setNomGb("Spain");

        $this->addReference('_reference_Pays_203', $item203);

        $manager->persist($item203);

        $item204 = new Pays();
        $item204->setAlpha("EH");
        $item204->setNomFr("Sahara Occidental");
        $item204->setNomGb("Western Sahara");

        $this->addReference('_reference_Pays_204', $item204);

        $manager->persist($item204);

        $item205 = new Pays();
        $item205->setAlpha("SD");
        $item205->setNomFr("Soudan");
        $item205->setNomGb("Sudan");

        $this->addReference('_reference_Pays_205', $item205);

        $manager->persist($item205);

        $item206 = new Pays();
        $item206->setAlpha("SR");
        $item206->setNomFr("Suriname");
        $item206->setNomGb("Suriname");

        $this->addReference('_reference_Pays_206', $item206);

        $manager->persist($item206);

        $item207 = new Pays();
        $item207->setAlpha("SJ");
        $item207->setNomFr("Svalbard etÎle Jan Mayen");
        $item207->setNomGb("Svalbard and Jan Mayen");

        $this->addReference('_reference_Pays_207', $item207);

        $manager->persist($item207);

        $item208 = new Pays();
        $item208->setAlpha("SZ");
        $item208->setNomFr("Swaziland");
        $item208->setNomGb("Swaziland");

        $this->addReference('_reference_Pays_208', $item208);

        $manager->persist($item208);

        $item209 = new Pays();
        $item209->setAlpha("SE");
        $item209->setNomFr("Suède");
        $item209->setNomGb("Sweden");

        $this->addReference('_reference_Pays_209', $item209);

        $manager->persist($item209);

        $item210 = new Pays();
        $item210->setAlpha("CH");
        $item210->setNomFr("Suisse");
        $item210->setNomGb("Switzerland");

        $this->addReference('_reference_Pays_210', $item210);

        $manager->persist($item210);

        $item211 = new Pays();
        $item211->setAlpha("SY");
        $item211->setNomFr("République Arabe Syrienne");
        $item211->setNomGb("Syrian Arab Republic");

        $this->addReference('_reference_Pays_211', $item211);

        $manager->persist($item211);

        $item212 = new Pays();
        $item212->setAlpha("TJ");
        $item212->setNomFr("Tadjikistan");
        $item212->setNomGb("Tajikistan");

        $this->addReference('_reference_Pays_212', $item212);

        $manager->persist($item212);

        $item213 = new Pays();
        $item213->setAlpha("TH");
        $item213->setNomFr("Thaïlande");
        $item213->setNomGb("Thailand");

        $this->addReference('_reference_Pays_213', $item213);

        $manager->persist($item213);

        $item214 = new Pays();
        $item214->setAlpha("TG");
        $item214->setNomFr("Togo");
        $item214->setNomGb("Togo");

        $this->addReference('_reference_Pays_214', $item214);

        $manager->persist($item214);

        $item215 = new Pays();
        $item215->setAlpha("TK");
        $item215->setNomFr("Tokelau");
        $item215->setNomGb("Tokelau");

        $this->addReference('_reference_Pays_215', $item215);

        $manager->persist($item215);

        $item216 = new Pays();
        $item216->setAlpha("TO");
        $item216->setNomFr("Tonga");
        $item216->setNomGb("Tonga");

        $this->addReference('_reference_Pays_216', $item216);

        $manager->persist($item216);

        $item217 = new Pays();
        $item217->setAlpha("TT");
        $item217->setNomFr("Trinité-et-Tobago");
        $item217->setNomGb("Trinidad and Tobago");

        $this->addReference('_reference_Pays_217', $item217);

        $manager->persist($item217);

        $item218 = new Pays();
        $item218->setAlpha("AE");
        $item218->setNomFr("Émirats Arabes Unis");
        $item218->setNomGb("United Arab Emirates");

        $this->addReference('_reference_Pays_218', $item218);

        $manager->persist($item218);

        $item219 = new Pays();
        $item219->setAlpha("TN");
        $item219->setNomFr("Tunisie");
        $item219->setNomGb("Tunisia");

        $this->addReference('_reference_Pays_219', $item219);

        $manager->persist($item219);

        $item220 = new Pays();
        $item220->setAlpha("TR");
        $item220->setNomFr("Turquie");
        $item220->setNomGb("Turkey");

        $this->addReference('_reference_Pays_220', $item220);

        $manager->persist($item220);

        $item221 = new Pays();
        $item221->setAlpha("TM");
        $item221->setNomFr("Turkménistan");
        $item221->setNomGb("Turkmenistan");

        $this->addReference('_reference_Pays_221', $item221);

        $manager->persist($item221);

        $item222 = new Pays();
        $item222->setAlpha("TC");
        $item222->setNomFr("Îles Turks et Caïques");
        $item222->setNomGb("Turks and Caicos Islands");

        $this->addReference('_reference_Pays_222', $item222);

        $manager->persist($item222);

        $item223 = new Pays();
        $item223->setAlpha("TV");
        $item223->setNomFr("Tuvalu");
        $item223->setNomGb("Tuvalu");

        $this->addReference('_reference_Pays_223', $item223);

        $manager->persist($item223);

        $item224 = new Pays();
        $item224->setAlpha("UG");
        $item224->setNomFr("Ouganda");
        $item224->setNomGb("Uganda");

        $this->addReference('_reference_Pays_224', $item224);

        $manager->persist($item224);

        $item225 = new Pays();
        $item225->setAlpha("UA");
        $item225->setNomFr("Ukraine");
        $item225->setNomGb("Ukraine");

        $this->addReference('_reference_Pays_225', $item225);

        $manager->persist($item225);

        $item226 = new Pays();
        $item226->setAlpha("MK");
        $item226->setNomFr("L'ex-République Yougoslave de Macédoine");
        $item226->setNomGb("The Former Yugoslav Republic of Macedonia");

        $this->addReference('_reference_Pays_226', $item226);

        $manager->persist($item226);

        $item227 = new Pays();
        $item227->setAlpha("EG");
        $item227->setNomFr("Égypte");
        $item227->setNomGb("Egypt");

        $this->addReference('_reference_Pays_227', $item227);

        $manager->persist($item227);

        $item228 = new Pays();
        $item228->setAlpha("GB");
        $item228->setNomFr("Royaume-Uni");
        $item228->setNomGb("United Kingdom");

        $this->addReference('_reference_Pays_228', $item228);

        $manager->persist($item228);

        $item229 = new Pays();
        $item229->setAlpha("IM");
        $item229->setNomFr("Île de Man");
        $item229->setNomGb("Isle of Man");

        $this->addReference('_reference_Pays_229', $item229);

        $manager->persist($item229);

        $item230 = new Pays();
        $item230->setAlpha("TZ");
        $item230->setNomFr("République-Unie de Tanzanie");
        $item230->setNomGb("United Republic Of Tanzania");

        $this->addReference('_reference_Pays_230', $item230);

        $manager->persist($item230);

        $item231 = new Pays();
        $item231->setAlpha("US");
        $item231->setNomFr("États-Unis");
        $item231->setNomGb("United States");

        $this->addReference('_reference_Pays_231', $item231);

        $manager->persist($item231);

        $item232 = new Pays();
        $item232->setAlpha("VI");
        $item232->setNomFr("Îles Vierges des États-Unis");
        $item232->setNomGb("U.S. Virgin Islands");

        $this->addReference('_reference_Pays_232', $item232);

        $manager->persist($item232);

        $item233 = new Pays();
        $item233->setAlpha("BF");
        $item233->setNomFr("Burkina Faso");
        $item233->setNomGb("Burkina Faso");

        $this->addReference('_reference_Pays_233', $item233);

        $manager->persist($item233);

        $item234 = new Pays();
        $item234->setAlpha("UY");
        $item234->setNomFr("Uruguay");
        $item234->setNomGb("Uruguay");

        $this->addReference('_reference_Pays_234', $item234);

        $manager->persist($item234);

        $item235 = new Pays();
        $item235->setAlpha("UZ");
        $item235->setNomFr("Ouzbékistan");
        $item235->setNomGb("Uzbekistan");

        $this->addReference('_reference_Pays_235', $item235);

        $manager->persist($item235);

        $item236 = new Pays();
        $item236->setAlpha("VE");
        $item236->setNomFr("Venezuela");
        $item236->setNomGb("Venezuela");

        $this->addReference('_reference_Pays_236', $item236);

        $manager->persist($item236);

        $item237 = new Pays();
        $item237->setAlpha("WF");
        $item237->setNomFr("Wallis et Futuna");
        $item237->setNomGb("Wallis and Futuna");

        $this->addReference('_reference_Pays_237', $item237);

        $manager->persist($item237);

        $item238 = new Pays();
        $item238->setAlpha("WS");
        $item238->setNomFr("Samoa");
        $item238->setNomGb("Samoa");

        $this->addReference('_reference_Pays_238', $item238);

        $manager->persist($item238);

        $item239 = new Pays();
        $item239->setAlpha("YE");
        $item239->setNomFr("Yémen");
        $item239->setNomGb("Yemen");

        $this->addReference('_reference_Pays_239', $item239);

        $manager->persist($item239);

        $item240 = new Pays();
        $item240->setAlpha("CS");
        $item240->setNomFr("Serbie-et-Monténégro");
        $item240->setNomGb("Serbia and Montenegro");

        $this->addReference('_reference_Pays_240', $item240);

        $manager->persist($item240);

        $item241 = new Pays();
        $item241->setAlpha("ZM");
        $item241->setNomFr("Zambie");
        $item241->setNomGb("Zambia");

        $this->addReference('_reference_Pays_241', $item241);

        $manager->persist($item241);

    
        $manager->flush();
    }

}
