accueil_homepage:
    path:     /
    defaults: { _controller: AccueilBundle:Default:index }

reservation_date:
    path:     /reservation/
    defaults: { _controller: AccueilBundle:Reservation:date }

reservation_billet:
    path:     /reservation/{date}/{dj}/{places}
    defaults: { _controller: AccueilBundle:Reservation:billet }

recapitulatif:
    path:     /recap/{id}
    defaults: { _controller: AccueilBundle:Reservation:recap }

paiement:
    path:    /paiement/{id}
    defaults: { _controller: AccueilBundle:Reservation:paiement }
